### ISSUE TITLE
Win10 empty Settings window

### ISSUE THREAD

**Issue by jkdn0921s** [oOthkOo/whatsapp-desktop#51] opened 2024-01-18 10:49 UTC
### System details

* OS: Windows 10 Pro N, version 22H2, OS build 19045.3930
* App Version: latest version, couldn't see what in About (showing as empty), as of 18/1/2024

### Expected behavior

visible text on Settings

### Actual behavior

When trying to access Edit  > Settings, most of the text is blank and not visible

### Step to reproduce the behavior

I tried changing the theme from System, to Light to Dark, but getting same result, the settings is not visible. pls check screenshot.
![whatsapp desktop win10 - 1](https://github.com/oOthkOo/whatsapp-desktop/assets/139198315/b1eb4e5f-320e-4a8c-9a35-bc5762151631)
![whatsapp desktop win10 - 2](https://github.com/oOthkOo/whatsapp-desktop/assets/139198315/759d1359-c9ec-42a2-a2e3-e939f814cfaf)

**Comment by LoneDev6** [comment] 2024-02-14 12:13
Duplicate of https://github.com/oOthkOo/whatsapp-desktop/issues/44

**Comment by jkdn0921s** [comment] 2024-04-18 15:35
closing it, thx @LoneDev6

**Closed** 2024-04-18 15:35 UTC
